steps:
  # Trigger Playwright Tests Dynamically
  - command: |
      export SOMEVAR1=$(buildkite-agent meta-data get deploy-environment)
      echo $${SOMEVAR1}
      
  - wait      
  
  - label: ":playwright: Trigger Playwright Tests"
    trigger: "qa-playwright-tests-enterprise-portal-$(buildkite-agent meta-data get deploy-environment)"
    soft_fail: true
