- label: ":playwright: Trigger Playwright Tests"
  trigger: "qa-playwright-tests-enterprise-portal-${DEPLOY_ENVIRONMENT}"
  soft_fail: true
  build:
    message: "Triggered Playwright tests for ${BUILDKITE_BRANCH} deployment"
    branch: "master"
